### ISSUE TITLE
子包添加参数报错

### ISSUE THREAD

**Issue by xieyuanyou11** [gudqs7/wxappUnpacker#11]
C:\Users\Administrator\Desktop\pkg>node wuWxapkg.js re\_WxaPage_wxebaea9edfc283e7c_10102_41_653433641.wxapkg -s=re\\
Unpack file re\_WxaPage_wxebaea9edfc283e7c_10102_41_653433641.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  26
  dataLength:  17322
  lastMark: 0xed

File list info:
  fileCount:  1
Saving files...
Unpack done.
now dir: C:\Users\Administrator\Desktop\pkg\re\_WxaPage_wxebaea9edfc283e7c_10102_41_653433641
param of mainDir: re\\
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir 'C:\Users\Administrator\Desktop\pkg\re\_WxaPage_wxebaea9edfc283e7c_10102_41_653433641\widget.js'
    at Object.fs.readdirSync (fs.js:904:18)
    at findDir (C:\Users\Administrator\Desktop\pkg\wuWxapkg.js:154:36)
    at findDir (C:\Users\Administrator\Desktop\pkg\wuWxapkg.js:165:29)
    at Array.packDone (C:\Users\Administrator\Desktop\pkg\wuWxapkg.js:171:17)
    at CntEvent.decount (C:\Users\Administrator\Desktop\pkg\wuLib.js:20:54)
    at ioLimit.runWithCb.err (C:\Users\Administrator\Desktop\pkg\wuLib.js:96:17)
    at agent (C:\Users\Administrator\Desktop\pkg\wuLib.js:64:23)
    at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by gudqs7** [comment]
@xieyuanyou11  re\ 目录不存在吧
