### ISSUE TITLE
wuLib,js：86错误

### ISSUE THREAD

**Issue by shaofa6633** [gudqs7/wxappUnpacker#14]
```
wuLib,js：86错误 Windows运行包 但是有官方插件无法解包 如何解决
```

**Comment by wangxianglong** [comment]
> ```
> wuLib,js：86错误 Windows运行包 但是有官方插件无法解包 如何解决
> ```

是不是报这个错？
Error: Save file error: Error: ENOENT: no such file or directory, open 'F:\_1447495917_40\pages\campustalk\camlist\plugin:\wx92c68dae5a8bb046\calendar.json'
    at ioLimit.runWithCb.err (D:\wxappUnpacker\wuLib.js:86:24)
    at agent (D:\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1294:7
    at FSReqWrap.oncomplete (fs.js:149:20)

[_1447495917_40.zip](https://github.com/gudqs7/wxappUnpacker/files/3342031/_1447495917_40.zip)
