### ISSUE TITLE
windows系统下解包报错，用的原版可以解但是获取不到wxss

### ISSUE THREAD

**Issue by jihuoxia** [gudqs7/wxappUnpacker#17]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\H\AppData\Roaming\npm\node_modules\wxappUnpacker5\wuWxss.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

C:\Users\H\AppData\Roaming\npm\node_modules\wxappUnpacker5>
报错是啥情况，windows系统下用什么命令解包

**Comment by 2103539816** [comment]
联系QQ7423385 可以付费解决
