### ISSUE TITLE
解压子包报错

### ISSUE THREAD

**Issue by wangxianglong** [gudqs7/wxappUnpacker#18]
解压子包时报错

程序执行命令(可选):
./bingo.sh F:/yinzhang/_1123949441_260.wxapkg  -s=F:/yinzhang/_440563806_15

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
node /d/wxappUnpacker/wuWxapkg.js
Unpack file F:/yinzhang/_1123949441_260.wxapkg...

Header info:
  firstMark: 0xbe
  unknownInfo:  0
  infoListLength:  434
  dataLength:  6564561
  lastMark: 0xed

File list info:
  fileCount:  16
Saving files...
Unpack done.
now dir: F:\yinzhang\_1123949441_260
param of mainDir: F:/yinzhang/_440563806_15
fs.js:924
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir 'F:\yinzhang\_1123949441_260\WAAutoService.js'
    at Object.fs.readdirSync (fs.js:924:18)
    at findDir (D:\wxappUnpacker\wuWxapkg.js:154:36)
    at findDir (D:\wxappUnpacker\wuWxapkg.js:165:29)
    at Array.packDone (D:\wxappUnpacker\wuWxapkg.js:171:17)
    at CntEvent.decount (D:\wxappUnpacker\wuLib.js:20:54)
    at ioLimit.runWithCb.err (D:\wxappUnpacker\wuLib.js:87:17)
    at agent (D:\wxappUnpacker\wuLib.js:64:23)
    at FSReqWrap.oncomplete (fs.js:149:20)

```

其他附加内容:
紧急求助啊大神！
[测试小程序包.zip](https://github.com/gudqs7/wxappUnpacker/files/3339122/default.zip)

**Comment by wangxianglong** [comment]
> 解压子包时报错
> 
> 程序执行命令(可选):
> ./bingo.sh F:/yinzhang/_1123949441_260.wxapkg -s=F:/yinzhang/_440563806_15
> 
> 程序执行错误信息(如果反馈是抛出异常的错误，必填):
> 
> ```
> node /d/wxappUnpacker/wuWxapkg.js
> Unpack file F:/yinzhang/_1123949441_260.wxapkg...
> 
> Header info:
>   firstMark: 0xbe
>   unknownInfo:  0
>   infoListLength:  434
>   dataLength:  6564561
>   lastMark: 0xed
> 
> File list info:
>   fileCount:  16
> Saving files...
> Unpack done.
> now dir: F:\yinzhang\_1123949441_260
> param of mainDir: F:/yinzhang/_440563806_15
> fs.js:924
>   return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
>                  ^
> 
> Error: ENOTDIR: not a directory, scandir 'F:\yinzhang\_1123949441_260\WAAutoService.js'
>     at Object.fs.readdirSync (fs.js:924:18)
>     at findDir (D:\wxappUnpacker\wuWxapkg.js:154:36)
>     at findDir (D:\wxappUnpacker\wuWxapkg.js:165:29)
>     at Array.packDone (D:\wxappUnpacker\wuWxapkg.js:171:17)
>     at CntEvent.decount (D:\wxappUnpacker\wuLib.js:20:54)
>     at ioLimit.runWithCb.err (D:\wxappUnpacker\wuLib.js:87:17)
>     at agent (D:\wxappUnpacker\wuLib.js:64:23)
>     at FSReqWrap.oncomplete (fs.js:149:20)
> ```
> 
> 其他附加内容:
> 紧急求助啊大神！
> [测试小程序包.zip](https://github.com/gudqs7/wxappUnpacker/files/3339122/default.zip)

我认真看了下源码和这个子包  好像是子包搞错了  这个不是子包。
