### ISSUE TITLE
wuLib.js:86:24报错

### ISSUE THREAD

**Issue by wangxianglong** [gudqs7/wxappUnpacker#19]
程序执行命令(可选):

程序执行错误信息(如果反馈是抛出异常的错误，必填):

```
D:\wxappUnpacker\wuLib.js:86
        if (err) throw Error("Save file error: " + err);
                 ^

Error: Save file error: Error: ENOENT: no such file or directory, open 'F:\_1447495917_40\plugin-private:\wx92c68dae5a8bb046\plugin.json'
    at ioLimit.runWithCb.err (D:\wxappUnpacker\wuLib.js:86:24)
    at agent (D:\wxappUnpacker\wuLib.js:64:23)
    at fs.js:1294:7
    at FSReqWrap.oncomplete (fs.js:149:20)

```

执行命令报这个错。大神紧急求助啊！附件是小程序包。
[_1447495917_40.zip](https://github.com/gudqs7/wxappUnpacker/files/3342044/_1447495917_40.zip)

**Comment by wangxianglong** [comment]
应该是日历插件也打包在wxapkg里面了，这个怎么解决啊？大神求助！

**Comment by Paladinhanxiao** [comment]
Error: Save file error: Error: ENOENT: no such file or directory, open 'D:\Project\cark\test\_-40744042_126\plugin-private:\wx2d2cd5fd79 396601\plugin.json'                                                                                                                          at ioLimit.runWithCb.err (D:\Project\cark\wxappUnpacker-master\wuLib.js:86:24)                                                           at agent (D:\Project\cark\wxappUnpacker-master\wuLib.js:64:23)                                                                           at fs.js:1170:7                                                                                                                          at FSReqWrap.oncomplete (fs.js:141:20)
--

**Comment by 1553105644** [comment]
可以联系QQ7423385  可以付费解决

**Comment by JavaToNull** [comment]
解决了吗 这个错误，求告知

**Comment by 1376134288** [comment]
求告知求告知，一样的错误
